### ISSUE TITLE
Since 17.07.2015 cant login

### ISSUE THREAD

**Issue by sushi86** [sanderdriesen/WhatsAPINet#10]
With each login I get:

Login failed. Reason: not-authorized

yowsup is working fine, but I have to update it, before I get the same error. Some Whattsapp API Changes?

greetz

**Comment by MarneeDear** [comment]
Having the same problem here.  I can confirm that my number and password are working on yowsup.

**Comment by sanderdriesen** [comment]
Thanks for reporting this issue. I just pushed the fix for this issue.

**Comment by sushi86** [comment]
Thanks for this fast fix!

**Comment by sanderdriesen** [comment]
You're welcome!
