### ISSUE TITLE
1st Time WhatsApp API sending message but second time it is not sending message

### ISSUE THREAD

**Issue by sujeet-bhujbal** [sanderdriesen/WhatsAPINet#15]
Hi Team,

I am using WhatsApp API for one of the requirement , when 1st time i am sending any whats-app message it is sending correctly but when second time i am sending message it is showing success message but message is not delivered to recipient whats-app inbox.

Please let me know what is wrong happening

**Comment by janpieterz** [comment]
Hi @sujit9923. 

Could you provide some more information on how you set your code up? Is it every first time you run the code? Or is it every first time with a new number? Or every first time with a new message?

If it is every first time you run the code it seems like you're implementation is missing certain parts. Perhaps you can debug your code and watch the locals deep inside WhatsApi to see if there are any differences between your first run and your second run! There must be a difference somewhere, and it's very difficult for us to help you with that.

**Comment by sujeet-bhujbal** [comment]
Hi janpieterz ,

I already sent messages by using Whatsapp code but now My Whatsapp account has been blocked by whatsapp getting error whatsapp is no longer allowed to use our service.

Why this happen???

**Comment by janpieterz** [comment]
Hi @sujit9923 

Sadly we can't help you any further in that case. Please check http://www.whatsapp.com/legal/.
