### ISSUE TITLE
i'm receiving not-authorized error loging

### ISSUE THREAD

**Issue by abu-sraag** [sanderdriesen/WhatsAPINet#17]
i am download link this : https://www.nuget.org/packages/WhatsAppAPI

and this code :

WhatsApp wa = new WhatsApp(MyNumber, Mypassword, nickname, false,false);
            wa.OnConnectSuccess += () =>
            {
                MessageBox.Show("Connected");
                wa.OnLoginSuccess += (phoneNumber, data) =>
                {
                    MessageBox.Show("Connection success!");
                    wa.SendMessage(tBto.Text,tBtext.Text);
                    MessageBox.Show("Message sent!");
                };
                wa.OnLoginFailed += (data) =>
                {
                    MessageBox.Show("Login failed: {0}", data);
                };
                wa.Login();
            };
            wa.OnConnectFailed += (ex) =>
            {
                MessageBox.Show("Connect failed: {0}", ex.StackTrace);
            };
            wa.Connect();

```
        MessageBox.Show("END");
```

---

what is wrong !!

**Comment by janpieterz** [comment]
Hi @abu-sraag.
We're not responsible for that nuget package (if you follow the link[1] you'll also see that it goes to the repository of andregsilv who forked it from us).
If you'd like to try our code I suggest downloading it and building it yourself, it should be pretty straightforward since it's just a Visual Studio project. That build will give you the dll you'd like to use, otherwise I suggest asking andregsilv for some help!

[1] https://github.com/andregsilv/WhatsAPINet

**Comment by janpieterz** [comment]
As a sidenote, we've fixed an issue that sounds very similar recently in this repository, so I think if you update to our version you might get it working! At least worth a shot ;)

**Comment by abu-sraag** [comment]
Already updated to the latest version but it seems that the file is updated from the source

I download from the link, but did not know the method of operation and the recall, and there are several projects within the project just need the transmission process, what's the class or do I need if you indicate to me that Thank you for your response

**Comment by abu-sraag** [comment]
I've I copy the file dll from folder to folder Debug To source and worked successfully 
Thanks you dear :)

I have several questions
1. How can I check the numbers that enabled them whatsapp August as a process of examination.
   ex : number : 999xxxxxx enable whatsapp or not ?
2. How do I know the message arrived or not.

3 - the maximum in order to send are not taken to ban the figure whether the number of messages / time.

If you could answer me I'm very thankful to you

**Comment by janpieterz** [comment]
Hi @abu-sraag 

We're unable to provide you with this kind of support, sorry!
Please familiarize yourself with other repositories out there, the sample projects in the code and besides that just reading the code.
