### ISSUE TITLE
lost connection after some minutes

### ISSUE THREAD

**Issue by bekeer020** [sanderdriesen/WhatsAPINet#19]
Hi sanderdriesen 
i use Whats Test Project "console application"
it is working fine with me send and receive no problem
but after some minutes i lost the connection ,i can not receive any message from others.
my question is how to keep it live? ,i want any time can receive messages from other numbers

**Comment by janpieterz** [comment]
I'm sorry, this sounds like a local issue. Please check how your machine handles the socket.
