### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by kunalsmehtajobs** [sanderdriesen/WhatsAPINet#28]
Hi,
I am getting the Login Failed error.
It was working till yesterday.
May be the whatsapp version is updated.
Can you check this?
Regards
Kunal

**Comment by PeterHunt** [comment]
Same issue here :(

**Comment by kunalsmehtajobs** [comment]
I feel the WhatsApp version is changed to 2.13.21. Can anyone let me know what are the other things we need to change?

**Comment by kunalsmehtajobs** [comment]
Cahnge these files and the issue is fixed

WhatsConstants.cs

public const string WhatsAppVer = "2.13.21";//"2.12.96";
public const string UserAgent = "WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302";

WaToken.cs
string token = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073" + number;

**Comment by abhith** [comment]
I had the same problem. 
Its been solved by using the current github project build of WhatsAPINet rather than the NuGet package.
