### ISSUE TITLE
Incoming Messages are encrypted

### ISSUE THREAD

**Issue by KapteinBabbalas** [sanderdriesen/WhatsAPINet#29]
Hi Guys, just noticed that my incoming messages are now encrypted for some reason.It started doing this a few hours ago, WhastApp probably changed something.I also noticed that not all my numbers are affected but only some of them. I also tested this on the mgp25/Chat-API-NET version..also doing the same thing there.

**Comment by yniv** [comment]
Yep...  the c# API's doesn't support the axolotl encryption. WhatsApp finally rolled the change to make all numbers use encryption. SO, until chat-api-net or any other c# api will support it they are all useless.... :-/

**Comment by kunalsmehtajobs** [comment]
Can sombody fix this issue? Any updates on the same? I mean, is sombody working on this?

**Comment by KapteinBabbalas** [comment]
I just received a crappy response from mgp25/Chat-API-NET regarding this issue:

"this normal, read other issues. The .NET API doesnt support E2E encryption, if you want to read encrypted messages use the php API"...so I guess nobody cares about this? Its strange because I've been using this API for a year and only now it is receiving messages as encrypted.

**Comment by janpieterz** [comment]
People probably care about this, but don't have the time and resources (read: money) to invest in fixing it. To keep this project up and running costs quite a lot of time which, speaking for myself, I simply don't have for quite some time of the near future, paying customers have precedence over hobby projects ;)

**Comment by KapteinBabbalas** [comment]
I'm a .Net developer with 3.5 years experience and I have the time to do this, but not the understanding of what exactly to do. If somebody can guide me I would be glad to spend some time on this. Anybody who understands what needs to be done but don't have the time/money can contact me.I see that there are some guys in the Netherlands, I'm also in the Netherlands so maybe we can meet sometime and discuss this.

**Comment by janpieterz** [comment]
@KapteinBabbalas I'd say take a good look at why the PHP one works and ours not. There must be some decryption and encryption stack there that takes care of handling this, which probably would be just in front and after sending / receiving it to WhatsApp. I have nothing more specific, but I'd take the PHP source and dig there, compare entry points to WhatsApp and work with it from there.

**Comment by janpieterz** [comment]
You can easily fork this repo and start your own since you seem to be quite active!

**Comment by KapteinBabbalas** [comment]
From what I can see is that the PHP lib uses 'libaxolotl-php' to handle the encryption, the WhatsApp .Net version does not have that.I also looked for a .net version of TextSecure and found this https://github.com/hope15/TextSecure-PC.NET  but it looks outdated. We need to implement TextSecure in some way. Any suggestions? Update..found this: https://github.com/langboost/libaxolotl-uwp which looks more promising

**Comment by janpieterz** [comment]
Second one seems better (only because it is newer). I don't have any insight in which one would work best. Keep in mind that you're going to have to maintain the dependency so checking with the authors to see if they still actively support it is probably a good idea.

**Comment by kunalsmehtajobs** [comment]
Please do the needful to integrate the same. Php one seems to work fine

**Comment by kunalsmehtajobs** [comment]
@KapteinBabbalas: Mine is not even getting logged in. Please guide me how do I successfully log in.

**Comment by fanducoder** [comment]
is anyone working on encrypted messages issue ?

**Comment by KoosKombuis** [comment]
I think mgp25 is busy with it. read this https://github.com/mgp25/Chat-API-NET/issues/134

**Comment by thiagoxti** [comment]
I think that for all this is pretty important . So I see that one of the problems is that there is no time or money. I think every person here has an interest should help . I propose a donation to to solve this problem . My part will be $ 100.00, by paypal.

I know it's little, but if everyone who is interested do it well , it will be very good.

**Comment by KapteinBabbalas** [comment]
There has been some progress, looks like there is only a few small but crucial changes to be made.
https://github.com/mgp25/Chat-API-NET/pull/142

**Comment by thiagoxti** [comment]
Thanks @KapteinBabbalas

**Comment by khaledsalama** [comment]
Is there any update regarding this issue?
