### ISSUE TITLE
Not-Authorized

### ISSUE THREAD

**Issue by eaba** [sanderdriesen/WhatsAPINet#4]
How can I overcome the issue of Not-Authorized?

**Comment by sanderdriesen** [comment]
By signing in properly ;)

**Comment by eaba** [comment]
I had to create an account which prompted me with the 'password'; i was using the wrong 'password', now signing in properly;
Please, i am able to send message; but when it is replied i cant see it or the app does not read it.

can i use this in windows service to push messages to contacts?

**Comment by janpieterz** [comment]
Yes you surely can @eaba. You can see in the test application and in the port how to work with the API.

**Comment by eaba** [comment]
I really want to do enterprise stuffs with it; like sending messages to hundreds of contacts at once; is there anything i need to pay attention to? Would whatsapp allow such? Do i stand a risk of being blocked?

**Comment by janpieterz** [comment]
I would really look to what type of messages you'd be sending. Terms of conditions of the original one state that it should not be used for marketing or massive amounts of messages. Be careful and only use it for legitimate purposes. Spamming 100s of contacts at once certainly isn't. Sorry I can't help you further in this.

**Comment by eaba** [comment]
Thanks. Am not using it for marketing. A2P stuff; I currently have a system where birthdays are sent to contacts using bulk sms and which allows user to send data to the system via sms. I just want users to be able to use whatsapp to do that in other to reduce user's cost. Please let me know if this is illegitimate? 
Please kindly inform me on the max number of contacts one can push messages to at once and at what interval? Thanks

**Comment by janpieterz** [comment]
I'd be very careful with the nature of your messages and read more about this and possible consequences. I'm not able to tell you specifically if your use case would run the risk of being blocked.

**Comment by eaba** [comment]
Please kindly direct me to relevant resources for this. Thanks

**Comment by janpieterz** [comment]
There you go. Long document but should give you what you need.
http://www.whatsapp.com/legal/

**Comment by eaba** [comment]
Hey! I appreciate your time spent replying me. thanks. I will go through the doc.
