### ISSUE TITLE
WhatsAPI Net - Keep it alive !

### ISSUE THREAD

**Issue by KapteinBabbalas** [sanderdriesen/WhatsAPINet#7]
Hi Sander,
I would like to contribute to the .net version of WhatsApi.
I have been using it for a while ,  but I see that people are removing it from their repo's because of threats from WhatsApp ( guys like Team Venomous )
It would be a shame to see this project die.
Will you send me a personal message to discuss this further?

**Comment by sanderdriesen** [comment]
Hi @KapteinBabbalas, 
As a contribution you are always welcome to submit any pull requests. We will submit your change to the fork after reviewing.

**Comment by urfrndsandy** [comment]
Dear Devs there is an error in WhatsMessageHandler at line 42 that says serverNickname is not in the context, may be another cs file was missed in the commit. @KapteinBabbalas can you fix this please?
Also two events for OnGetMessage are not fixed.

**Comment by KapteinBabbalas** [comment]
Hi @sanderdriesen I'll have a look at it

**Comment by KapteinBabbalas** [comment]
Hi Sander

I fixed it, sent you a pull request.

Pieter

**Comment by urfrndsandy** [comment]
@KapteinBabbalas  thanks a ton bro, i think Sander is busy with something, if it is allowed can you send me the updated .cs or lines or the package? please..

**Comment by KapteinBabbalas** [comment]
Hi

Cool no problem, glad I could help.
I cannot send the package as Gmail blocks the attachment.

Here is a dropbox link for the entire solution
https://www.dropbox.com/s/dww3ctonjzcfrml/WhatsAPINet.rar?dl=0
The fixes was in the WhatsTest project--events that needed extra parameters.
In the WhatsAppPort project -- a reference to a  "serverName' string that
was renamed in the Api itself.

**Comment by urfrndsandy** [comment]
@KapteinBabbalas thanks a Tonne... but still am unable to make it receive messages. Can you help me on that please.. I have added OnMessage recieved event and also have an event defined to handle messages but it doesnt seem to work

**Comment by KapteinBabbalas** [comment]
Did you manage to get it to work?

**Comment by urfrndsandy** [comment]
@KapteinBabbalas  no bro not yet.. and not sure why aint getting messages

**Comment by urfrndsandy** [comment]
@KapteinBabbalas bro can you get messages in the current issue?

**Comment by KapteinBabbalas** [comment]
Yes I can, double check that you are actually logged in, not just connected.
Step through the code at the part where it logs in, then check the connection status.

**Comment by urfrndsandy** [comment]
Thanks bro.. i will try that and let you know.

On Mon, Aug 24, 2015 at 1:02 PM, KapteinBabbalas notifications@github.com
wrote:

> Yes I can, double check that you are actually logged in, not just
> connected.
> Step through the code at the part where it logs in, then check the
> connection status.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sanderdriesen/WhatsAPINet/issues/7#issuecomment-134072427
> .

##

**Comment by KapteinBabbalas** [comment]
Hi Sander

I have problems logging in my numbers this morning, even after I used the
latest version of the code and register I get an unauthorized message.
Maybe Whats App changed something, because the numbers are not blocked.

Just want to know if anybody else have these issues today

**Comment by urfrndsandy** [comment]
@KapteinBabbalas  yes bro.. same problem here..

**Comment by urfrndsandy** [comment]
@KapteinBabbalas also surprisingly https://github.com/mgp25/Chat-API-NET is working...

**Comment by KapteinBabbalas** [comment]
I also noticed that

**Comment by urfrndsandy** [comment]
@KapteinBabbalas did you manage to parse incoming messages?

**Comment by KapteinBabbalas** [comment]
Hi Sander

I could receive incoming messages since I couldn't log in, with the
CHAT-API-NET code it everything worked as it should.

**Comment by urfrndsandy** [comment]
@KapteinBabbalas can you share the method used to parse messages?

**Comment by KapteinBabbalas** [comment]
I couldn't parse incoming messages,I'm trying to see the difference between CHAT-API and WhatsAPINET in the login process

**Comment by KapteinBabbalas** [comment]
Hi Sander

Looks like they (WhatsApp) changed something again, getting unauthorized
message again.
The mgp25/Chat-API-NET also gives the same error. Are you also having this
issue?

**Comment by SkullyDev** [comment]
Same here
Can't reregister with WART... Tells "old_version"

**Comment by KapteinBabbalas** [comment]
Hi Guys

Got the  mpg25/chat-api working by just updating the new constants values
that is used in the original PHP lib.
But when I tried to make the changes in this one , it still won't work.

**Comment by urfrndsandy** [comment]
@KapteinBabbalas can you please guide me what exactly you changed?

**Comment by KapteinBabbalas** [comment]
Hi

Shure no probs:

In the file WhatsAppApi/Settings:

public const string WhatsAppVer = "2.13.21";
public const string UserAgent = "WhatsApp/2.13.21 S40Version/14.26
Device/Nokia302";

thats it.

**Comment by urfrndsandy** [comment]
@KapteinBabbalas thank you!!!.. it worked perfectly to me.

**Comment by PeterHunt** [comment]
Works for me as well, thanks!

**Comment by urfrndsandy** [comment]
@PeterHunt can you receive the messages?

**Comment by PeterHunt** [comment]
No, that is the other issue; encryption. Sending is no problem.

**Comment by urfrndsandy** [comment]
am having a hard time receiving messages, can someone help me on this?

**Comment by PeterHunt** [comment]
Don't you receive anything at all, or gibberish?

**Comment by urfrndsandy** [comment]
i dont receive anything. Could you parse it? if so could you please share the code.

**Comment by SkullyDev** [comment]
@KapteinBabbalas hey where do you find these version strings, if not a secret just to know on future? :D

**Comment by KapteinBabbalas** [comment]
https://github.com/WHAnonymous/Chat-API

**Comment by urfrndsandy** [comment]
hi Guys.. it has stopped working again.. any solutions this time? @KapteinBabbalas @PeterHunt @sanderdriesen

**Comment by PeterHunt** [comment]
It stopped working for me as well about a month ago. Actually I gave up on this API more or less...

**Comment by urfrndsandy** [comment]
no other way out?

**Comment by KapteinBabbalas** [comment]
I have also given up on this. WhatsApp is in the process of making a public api (for Business use ) available. [http://www.forbes.com/sites/parmyolson/2016/01/18/whatsapp-businesses-free-1-billion/#21049f95b6bd](url)

If you want to build bots, Microsoft has realeased a bot framework from where you can create bots and just connect the bot to multiple platforms, like skype for example. [https://dev.botframework.com/](url)

Facebook also has an official Messenger api that you also can hook up (manually) to the bot framework. [https://developers.facebook.com/products/messenger/](url)
Who knows maybe in a short while there will be a WhatsApp bot connector as well.

**Comment by urfrndsandy** [comment]
Thanks @KapteinBabbalas .. sadly.. end of our projects.

**Comment by PeterHunt** [comment]
For what it's worth, my application connects fine, but after +/- 1 minute
it closes with a "stream error".

rx /stream:error
02-05-2016 - 17:19:58 - [Connect] Connected..
02-05-2016 - 17:19:58 - [Debug]

Within that minute I can send messages...

2016-05-02 11:55 GMT+02:00 urfrndsandy notifications@github.com:

**Comment by urfrndsandy** [comment]
@PeterHunt now even the WART is not working for me to test it :( sad that we are near to the end.

**Comment by urfrndsandy** [comment]
any update guys? yowsup is working fine by the way
