### ISSUE TITLE
Receiving messages isn't working

### ISSUE THREAD

**Issue by dholakiyaankit** [sanderdriesen/WhatsAPINet#8]
Hey, I just see that receiving messages isn't working....is this not possible? or should I invoke some method to retrieve it?

**Comment by ccejas** [comment]
Hi! In the project WhatsTest you have an example that explain how to use

**Comment by sanderdriesen** [comment]
@dholakiyaankit can you confirm whether the comment of @ccejas helped you out with receiving images?

**Comment by dholakiyaankit** [comment]
@sanderdriesen  not really.

**Comment by sanderdriesen** [comment]
Can you share your code and some more information about what you tried so we can help you out?

**Comment by dholakiyaankit** [comment]
@sanderdriesen  actually I don't have it. I tried this demo. it is working fine for sending messages. but I realized there is no code for receiving messages. can you show me some code/logic/demo for this?

**Comment by sanderdriesen** [comment]
There are some events available in the WhatsApp class indicating that a message is received. You can use it like this:

```
private void Init()
{
   _wa = new WhatsApp(MobileNumber, _password, Nickname, true);
   _wa.OnGetMessage += OnGetMessage;
}

private void OnGetMessage(ProtocolTreeNode messagenode, string @from, string id, string name, string message, bool receipt_sent)
{

}
```

Is this what you was looking for?

**Comment by dholakiyaankit** [comment]
@sanderdriesen  yeah actually. Thanks for the help. I will checkout later and will let you know.
